# Generated by Django 5.0.6 on 2024-06-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilemanagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_mail",
        ),
    ]
