# Generated by Django 5.0.6 on 2024-06-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilemanagement", "0002_remove_userprofile_user_mail"),
        ("wishlists", "0006_alter_item_quantity_alter_wishlist_occassion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_wish_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wishlists.wishlist",
            ),
        ),
    ]
