# Generated by Django 5.0.6 on 2024-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_wishlist_occassion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
